import type { ProofReceipt } from '../../types';

export function generateTextReceipt(receipt: ProofReceipt): string {
  const statusEmoji = receipt.verificationStatus === 'valid' ? '[VALID]' : '[INVALID]';
  const divider = '='.repeat(60);

  return `${divider}
                 DOCUMENT VERIFICATION RECEIPT
${divider}

Status: ${statusEmoji} ${receipt.verificationStatus.toUpperCase()}

Document Information:
  Title:      ${receipt.title}
  ${receipt.originalFilename ? `Filename:   ${receipt.originalFilename}\n  ` : ''}Hash:       ${receipt.documentHash}

Signature Information:
  Signed At:  ${receipt.signatureTimestamp}
  Signer ID:  ${receipt.signerFingerprint}

Verification:
  Verified:   ${receipt.verifiedAt}

${divider}
This receipt was generated by OVD (Open Verifiable Documents)
${divider}
`;
}

export function generateHtmlReceipt(receipt: ProofReceipt): string {
  const statusColor = receipt.verificationStatus === 'valid' ? '#22c55e' : '#ef4444';
  const statusText = receipt.verificationStatus === 'valid' ? 'VALID' : 'INVALID';

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Verification Receipt - ${receipt.title}</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      max-width: 600px;
      margin: 40px auto;
      padding: 20px;
      background: #f9fafb;
      color: #111827;
    }
    .receipt {
      background: white;
      border-radius: 12px;
      padding: 32px;
      box-shadow: 0 1px 3px rgba(0,0,0,0.1);
    }
    .header {
      text-align: center;
      margin-bottom: 24px;
    }
    .status {
      display: inline-block;
      padding: 8px 16px;
      border-radius: 9999px;
      font-weight: 600;
      font-size: 14px;
      color: white;
      background: ${statusColor};
    }
    h1 {
      margin: 16px 0 0;
      font-size: 20px;
      font-weight: 600;
    }
    .section {
      margin: 24px 0;
      padding: 16px;
      background: #f9fafb;
      border-radius: 8px;
    }
    .section-title {
      font-size: 12px;
      font-weight: 600;
      text-transform: uppercase;
      color: #6b7280;
      margin-bottom: 12px;
    }
    .field {
      margin: 8px 0;
    }
    .field-label {
      font-size: 12px;
      color: #6b7280;
    }
    .field-value {
      font-family: 'SF Mono', Monaco, monospace;
      font-size: 13px;
      word-break: break-all;
    }
    .footer {
      text-align: center;
      margin-top: 24px;
      padding-top: 16px;
      border-top: 1px solid #e5e7eb;
      font-size: 12px;
      color: #9ca3af;
    }
  </style>
</head>
<body>
  <div class="receipt">
    <div class="header">
      <span class="status">${statusText}</span>
      <h1>Document Verification Receipt</h1>
    </div>

    <div class="section">
      <div class="section-title">Document Information</div>
      <div class="field">
        <div class="field-label">Title</div>
        <div class="field-value">${escapeHtml(receipt.title)}</div>
      </div>
      ${receipt.originalFilename ? `
      <div class="field">
        <div class="field-label">Original Filename</div>
        <div class="field-value">${escapeHtml(receipt.originalFilename)}</div>
      </div>` : ''}
      <div class="field">
        <div class="field-label">Document Hash (SHA-256)</div>
        <div class="field-value">${receipt.documentHash}</div>
      </div>
    </div>

    <div class="section">
      <div class="section-title">Signature Information</div>
      <div class="field">
        <div class="field-label">Signed At</div>
        <div class="field-value">${receipt.signatureTimestamp}</div>
      </div>
      <div class="field">
        <div class="field-label">Signer Fingerprint</div>
        <div class="field-value">${receipt.signerFingerprint}</div>
      </div>
    </div>

    <div class="section">
      <div class="section-title">Verification</div>
      <div class="field">
        <div class="field-label">Verified At</div>
        <div class="field-value">${receipt.verifiedAt}</div>
      </div>
    </div>

    <div class="footer">
      Generated by OVD (Open Verifiable Documents)
    </div>
  </div>
</body>
</html>`;
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}
